export const ROUTES = {
  HOME: '/',
  TEACHER: '/teacher',
  ADMIN: '/admin',
  LOGIN: '/auth',
  PASSWORD: '/changePassword',
  RECOVERY: '/recovery',
  STUDYPLAN: '/studyplan',
  SUBJECT: '/subjects',
  TIPS: '/tips',
  TESTS: '/tests',
  QUIZ: '/quiz',
  ACHIEVEMENTS: '/achievements',
  EDITOR: '/editor',
  PANEL: '/panel',
  POMODORO: '/pomodoro',
  LIST_USERS: '/list/users',
  LIST_SUBJECTS: '/list/subjects',
  LIST_QUIZ: '/list/quiz',
  LIST_ACHIEVEMENTS: '/list/achievements',
  LIST_TIPS: '/list/tips',
  LIST_QUESTIONS: '/list/questions',
  LIST_LESSON: '/list/lesson',
  LIST_TOPIC: '/list/topics',
  LIST_ENEM: '/list/enem',
};
