import React from 'react';

import Head from 'next/head';
import Lesson from 'src/screens/List/Lesson';

const SubjectPageList = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Lista de todos usuários</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Lesson />
    </>
  );
};

export default SubjectPageList;
