import React from 'react';

import Head from 'next/head';
import Questions from 'src/screens/List/Questions';

const SubjectPageList = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>AjudaNois | Questões</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Questions />
    </>
  );
};

export default SubjectPageList;
