import React from 'react';

import Head from 'next/head';
import Users from 'src/screens/List/Users';

const SubjectPageList: React.FC = () => {
  return (
    <>
      <Head>
        <title>Lista de todos usuários</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Users />
    </>
  );
};

export default SubjectPageList;
