import React from 'react';

import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { withRouter } from 'next/router';
import SubjectContent from 'src/screens/SubjectContent';

const data = [
  {
    _id: '62b9c66c69e759068fc51e95',
    title: 'unifei libera acesso ',
    content:
      '<h1>UNIFEI LIBERA A PORRA DO ACESSO</h1><ul><li><p>SEU CORNO</p></li><li><p>AAAAAAAAA</p></li></ul><p></p><ol><li><p>ALO</p></li></ol><p></p><img src="https://firebasestorage.googleapis.com/v0/b/ajuda-nois.appspot.com/o/question%2Fquestion_1dc4b6ca-8c1b-453d-be33-5a9446db0382?alt=media&amp;token=e0002475-91b1-4d19-8ba8-3c332b0bb416">',
    topic_id: '62b8e08484c8fe761c2db14f',
    __v: 0,
    topic_info: {
      _id: '62b8e08484c8fe761c2db14f',
      name: 'Geometria',
      subject_id: '62b103f3f8652036c554dd8a',
      __v: 0,
    },
  },
];

function Pokemon({ details }: any): JSX.Element {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SubjectContent details={data[0]} />
    </>
  );
}

export default withRouter(Pokemon);
