import React from 'react';

import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { withRouter } from 'next/router';
import SubjectContent from 'src/screens/SubjectContent';

function Pokemon(): JSX.Element {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SubjectContent />
    </>
  );
}

export default Pokemon;
