export const COLORS = {
  PRIMARY: '#827AFD',
  SECONDARY: '#00BF20',
  TERTIARY: '#23232C',
  QUATERNARY: '#FFC13A',
  SUCCESS: '',
  WARNING: '',
  ERROR: '',
  NEUTRAL: '#2D2D35',
  WHITE: '#FFF',
  BLACK: '#CED4DA',
  TEXT: '#B4B4B4',
};
