import React from 'react';

import Head from 'next/head';
import Achievements from 'src/screens/Achievements';

const AchievementsPage = () => {
  return (
    <>
      <Head>
        <title>Suas conquistas</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Achievements />
    </>
  );
};

export default AchievementsPage;
