import type { NextPage } from 'next';
import Head from 'next/head';
import Password from 'src/screens/Password';

const Auth: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Password />
    </>
  );
};

export default Auth;
