import React from 'react';

import Head from 'next/head';

// import { Container } from './styles';

const Conquests = () => {
  return (
    <>
      <Head>
        <title>Suas conquistas</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Conquests</p>
    </>
  );
};

export default Conquests;
