import React from 'react';

import Head from 'next/head';
import Conquests from 'src/screens/Conquests';

const ConquestsPage = () => {
  return (
    <>
      <Head>
        <title>Suas conquistas</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Conquests />
    </>
  );
};

export default ConquestsPage;
