import React from 'react';

import Head from 'next/head';

import EditorContainer from '../src/components/Editor';

const EditorPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <EditorContainer showControls />
    </>
  );
};

export default EditorPage;
