import type { NextPage } from 'next';
import Head from 'next/head';

import { default as StudentDashboard } from '../src/screens/DashBoard/Student';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dash</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StudentDashboard />
    </>
  );
};

export default Home;
