import React from 'react';

import Head from 'next/head';

const PanelPage: React.FC = () => {
  return (
    <>
      <Head>
        <title>Subjects</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>panel</h1>
    </>
  );
};

export default PanelPage;
