import React from 'react';

import Head from 'next/head';
import Pomodoro from 'src/screens/Pomodoro';

const PomodoroPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Pomodoro />
    </>
  );
};

export default PomodoroPage;
