import React from 'react';

import Head from 'next/head';
import Quiz from 'src/screens/Quiz';

const QuizPage: React.FC = () => {
  return (
    <>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Quiz />
    </>
  );
};

export default QuizPage;
