import type { NextPage } from 'next';
import Head from 'next/head';
import Recovery from 'src/screens/Recovery';

const Auth: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Recovery />
    </>
  );
};

export default Auth;
