import React from 'react';

import Head from 'next/head';

import StudyPlan from '../src/screens/StudyPlan';

const StudyPlanPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Plano de Estudos</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StudyPlan />
    </>
  );
};

export default StudyPlanPage;
