import React from 'react';

import Head from 'next/head';
import Subjects from 'src/screens/Subjects';

const SubjectsPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Subjects</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Subjects />
    </>
  );
};

export default SubjectsPage;
