import React from 'react';

import Head from 'next/head';

// import { Container } from './styles';

const Subjects: React.FC = () => {
  return (
    <>
      <Head>
        <title>Subjects</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Subjects</p>
    </>
  );
};

export default Subjects;
