import React, { useEffect, useState } from 'react';

import Head from 'next/head';

import { default as TeacherDashboard } from '../src/screens/DashBoard/Teacher';

const TeacherPage = (): JSX.Element => {
  const [show, setShow] = useState(false);

  useEffect(() => {
    const type = localStorage.getItem('usertype');
    if (type === 'teacher') {
      setShow(true);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Dash</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      {show ? <TeacherDashboard /> : 'Você não tem permissão'}
    </>
  );
};

export default TeacherPage;
