import React from 'react';

import Head from 'next/head';

import { default as TeacherDashboard } from '../src/screens/DashBoard/Teacher';

const TeacherPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Dash</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TeacherDashboard />
    </>
  );
};

export default TeacherPage;
