import React from 'react';

import Head from 'next/head';
import Tests from 'src/screens/Tests';

const TestsPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Tests</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tests />
    </>
  );
};

export default TestsPage;
