import React from 'react';

import Head from 'next/head';

// import { Container } from './styles';

const Tips: React.FC = () => {
  return (
    <>
      <Head>
        <title>Tips</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Tips</p>
    </>
  );
};

export default Tips;
