import React from 'react';

import { GetServerSideProps } from 'next';
import Head from 'next/head';
import SubjectContent from 'src/screens/SubjectContent';

export default function Pokemon({ details }: any): JSX.Element {
  return (
    <>
      <Head>
        <title>{details.title}</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SubjectContent details={details} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const ctx = context.params;
  const res = await fetch('https://pokeapi.co/api/v2/pokemon/');
  const resjson = await res.json();

  const data = {
    id: ctx,
    sidebar: resjson.results,
    title: 'Matemática',
    html: `<p>HTML image tag</p>
  <p>Images are the most common element we see when we visit any website. Images make a website look more attractive. We can create images in HTML with a simple img tag. img tag is one such tag that has no closing tag. There are many attributes of the img tag which are useful in creating better-looking images in HTML. Two of these attributes are required in the img tag, src, and alt.</p>
  <img src="https://www.copahost.com/blog/wp-content/uploads/2019/07/imglink1.png" style="height:400px; width:400px"> 

   `,
  };

  return {
    props: {
      details: data,
    },
  };
};
