import React from 'react';

import Head from 'next/head';

const CreateSubject: React.FC = () => {
  return (
    <>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>create</h1>
    </>
  );
};

export default CreateSubject;
